remote_theme: pages-themes/primer@v0.6.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Site settings
title: PAELLADOC
tagline: Interactive Documentation System
description: An AI-powered interactive documentation system that uses natural language conversations to gather, generate and maintain project documentation.
baseurl: ""
url: "http://localhost:4000"
show_downloads: true
author: jlcases
logo: /assets/images/paelladoc-logo.png
lang: en_US

# Social media
social:
  name: PAELLADOC
  links:
    - https://github.com/jlcases/paelladoc

# SEO settings
twitter:
  username: jlcases
  card: summary_large_image

# Open Graph
og_image: /assets/images/paelladoc-logo.png
og_type: website

# Build settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project-layout"
  - scope:
      path: ""
    values:
      image: /assets/images/paelladoc-logo.png
      
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .DS_Store
  - docs
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .git
  - .github