# Development specific settings
url: "http://localhost:4000"
baseurl: ""

# Environment specific
environment: development

# Debug settings
verbose: true
profile: true

# Disable certain features in development
compress_html:
  ignore:
    envs: [development]

# Analytics disabled in development
google_analytics: null

# Redirect settings for development
redirect_from:
  enabled: true
  json: false
  redirects:
    - from: /index.html
      to: /es/
    - from: /home
      to: /es/ 