# Basic settings
title: PAELLA DOC
description: Sistema de documentación interactivo impulsado por IA
baseurl: ""
url: "http://localhost:4000"

# Uncomment these for GitHub Pages deployment
# baseurl: "/paelladoc"
# url: "https://jlcases.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-redirect-from

# Language settings
languages: ["es", "en"]
default_lang: "es"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE
  - "*.log"

# Default configuration
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Redirecciones principales
redirect_from:
  - /index.html
  - /home

# Configuración de Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X

# Sass configuration
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# Performance optimizations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Sitemap configuration
sitemap:
  enabled: true
  change_frequency_default: "weekly"
  priority_default: 0.5
  filename: "sitemap.xml"

# Custom colors
colors:
  primary: "#FFB800"
  secondary: "#CD9B1D"
  accent: "#D64045"
  text: "#1E1E24"
  background: "#F5F5F5"

# SEO and Social
social:
  name: PAELLA DOC
  links:
    - https://github.com/jlcases/paelladoc 