# Basic settings
title: PAELLA DOC
description: Sistema de documentación interactivo impulsado por IA

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-redirect-from
  - kramdown-parser-gfm

# Language settings
languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .git/
  - .github/

# Default configuration
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Sass configuration
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# Performance optimizations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

# Custom colors
colors:
  primary: "#FFB800"
  secondary: "#CD9B1D"
  accent: "#D64045"
  text: "#1E1E24"
  background: "#F5F5F5"

# Redirect settings
redirect_from:
  enabled: true
  json: false
  redirects:
    - from: /index.html
      to: /es/
    - from: /home
      to: /es/

# Configuración de Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X

# Sitemap configuration
sitemap:
  enabled: true
  change_frequency_default: "weekly"
  priority_default: 0.5
  filename: "sitemap.xml"

# SEO and Social
social:
  name: PAELLA DOC
  links:
    - https://github.com/jlcases/paelladoc 